services:
  - type: web
    name: laundry-system
    env: node
    plan: free
    buildCommand: |
      npm install -g pnpm
      pnpm install
      pnpm run build
    startCommand: pnpm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production